language: ruby
sudo: false
rvm:
  - 2.1
  - 2.2
  - 2.3
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  matrix:
    - RAILS_VERSION='~>4.1.10'
    - RAILS_VERSION='~>4.2.5'

before_install:
  - gem install bundler
  
notifications:
  irc: "irc.freenode.org#projectvov"
